version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    on-failure: ABORT
  pre_build:
    on-failure: ABORT
    commands:
      - echo "Logging in to ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY
  build:
    on-failure: ABORT
    commands:
      - echo "===== ENVIRONMENT $ENVIRONMENT ====="
      - echo "SOURCE VERSION $CODEBUILD_SOURCE_VERSION"
      - echo "RESOLVED VERSION $CODEBUILD_RESOLVED_SOURCE_VERSION"
      - echo "Building Docker image..."
      - docker build -t $IMAGE:$CODEBUILD_BUILD_NUMBER --target $TARGET .
      - if [[ "$ENVIRONMENT" == "prod" || "$ENVIRONMENT" == "beta" ]]; then echo "Tagging for beta/prod..." && docker tag $IMAGE:$CODEBUILD_BUILD_NUMBER $REPOSITORY/$IMAGE:$IMAGE_TAG && docker tag $IMAGE:$CODEBUILD_BUILD_NUMBER $REPOSITORY/$IMAGE:$CODEBUILD_BUILD_NUMBER; fi
      - if [[ "$ENVIRONMENT" == "dev" ]]; then echo "Tagging for dev environment..." && BRANCH=$(echo $CODEBUILD_SOURCE_VERSION | sed 's/[^a-zA-Z0-9]/-/g') && SHA=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7) && DEV_TAG="${BRANCH}-${SHA}" && echo "DEV TAG $DEV_TAG" && docker tag $IMAGE:$CODEBUILD_BUILD_NUMBER $REPOSITORY/$IMAGE:$DEV_TAG && echo $DEV_TAG > DEV_TAG.txt; fi
  post_build:
    on-failure: ABORT
    commands:
      - echo "Starting post-build phase..."
      - if [[ "$ENVIRONMENT" == "prod" || "$ENVIRONMENT" == "beta" ]]; then echo "Pushing prod/beta tags..." && docker push $REPOSITORY/$IMAGE:$IMAGE_TAG && docker push $REPOSITORY/$IMAGE:$CODEBUILD_BUILD_NUMBER && printf '[{"name":"app","imageUri":"%s"}]' $REPOSITORY/$IMAGE:$CODEBUILD_BUILD_NUMBER > imagedefinitions.json; fi
      - if [[ "$ENVIRONMENT" == "dev" ]]; then DEV_TAG=$(cat DEV_TAG.txt) && echo "Pushing dev tag $DEV_TAG" && docker push $REPOSITORY/$IMAGE:$DEV_TAG && printf '[{"name":"app","imageUri":"%s"}]' $REPOSITORY/$IMAGE:$DEV_TAG > imagedefinitions.json; fi
artifacts:
  files:
    - imagedefinitions.json